### ISSUE TITLE
puts you out of focus when you haven't clicked off then shoves all your tetris pieces to the right

### ISSUE THREAD

**Issue by nekowelsh** [tetrio/issues#1028] opened 2022-10-18 23:07 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 10

### Browser and version

chrome 106.0.5249.119

### Describe the bug/issue

i have been having this problem for a few weeks now, ill get into any game of solo and it will come up with the OUT OF FOCUS red warning and then when i click back on it, it shoves all my peices to the right or left, i cant get it to stop without reloading the website, cant play a game and i have no idea what's going on or how to fix it 

### Expected behavior

for the tetris pieces to move across the screen like they should instead of constantly going against players press of a button and forcing off to the right or left

**Comment by ZaptorZap** [comment] 2022-10-19 03:49
This is a duplicate of #123 and #680.

**Closed by ZaptorZap** 2022-10-19 03:49 UTC
Labels: bug
