### ISSUE TITLE
Tetrio Desktop sometimes freezes upon putting it in fullscreen.

### ISSUE THREAD

**Issue by FiFiFiZ** [tetrio/issues#1025] opened 2022-10-11 10:48 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11 

### Browser and version

21H2

### Describe the bug/issue

Pretty self-explanatory. I open tetr.io desktop, and it's up in the air if the graphics freeze or not. The game still works, i can for example hear the sound effects of hittings buttons, i can control my pieces midgame, but i can't see anything except the frame where i pressed f11 and i have to restart tetrio and the cycle continues, restarting sometimes fixes the issue but still very annoying.

### Reproducing

Open tetrio desktop, press f11. 

### Expected behavior

It should work as intended, sometimes it just works and sometimes it doesn't

### Screenshots

![image](https://user-images.githubusercontent.com/83916751/195069827-f089eea2-7d18-469b-bf85-dd15e95ade80.png)
this is how it looks when pressing f11

### Console logs

The screen is frozen and pressing f12 doesn't change anything either

**Comment by ZaptorZap** [comment] 2022-10-11 12:54
Seems to be a duplicate of #695 and **#656**, sorry about that

**Closed by ZaptorZap** 2022-10-11 12:54 UTC
Labels: bug
