### ISSUE TITLE
Board becomes 11x22 in handling settings test

### ISSUE THREAD

**Issue by aznguymp4** [tetrio/issues#492] opened 2020-09-28 22:14 UTC
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When clicking "TEST" in the settings to test out my handlings, the board was slightly larger at 11x22 blocks.

### Reproducing
1. Uninstall TETR.IO (Desktop)
2. Reinstall TETR.IO (Desktop)
3. Import a settings.ttc file
4. Drag the DCD slider, and test the handlings

### Expected behavior
The board to be 10x20 as expected

### Screenshots
This isn't a screenshot, but rather a video.
https://cdn.discordapp.com/attachments/698706837222195290/760261586610028544/wtf_.mp4

### Your setup
 - **OS and version**: Windows 10, version 2004
 - **Desktop Client**: version 5.0.0

**Comment by o5k** [comment] 2020-09-28 22:37
i cannot reproduce this, did you resize the window?

**Comment by o5k** [comment] 2020-12-16 00:19
Fixed in next patch.

**Closed by o5k** 2020-12-16 00:19 UTC
Labels: bug, needs-info
