### ISSUE TITLE
Zen Bag Issues

### ISSUE THREAD

**Issue by Jakeygoat** [tetrio/issues#1149] opened 2023-06-09 15:29 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome something or another

### Describe the bug/issue

Zen has bag errors when loading games.

### Reproducing

1. Whenever you're at the start of a bag in Zen (or the beginning of the game) the next piece (NOT in the next bar yet) should be whatever isn't in play or in the next queue.
2. Forfeit the game, then re-enter, and then suddenly the last piece in the bag is skipped.

### Expected behavior

I really don't know EXACTLY what's happening, and there's probably more problems it causes than just being at the start of a bag, but I think whenever you reload, it forgets everything about your bag, and simply gives you your next pieces and resets the bag.

### Screenshots

Forfeiting and re-entering when this is the start
![image](https://github.com/tetrio/issues/assets/30556680/b75299dc-013a-4b46-9c50-29927aeefaec)
results in the next game looking like this
![image](https://github.com/tetrio/issues/assets/30556680/002fff6b-07b3-48af-8fd0-6dcd4ea0df7f)
and the bag is missing the square :(

### Additional context

Apparently it also sometimes happens with undo and redo but I'm not sure. Can't it just remember where in the bag it is to solve this 🥺. Not exactly a high priority bug but it messes with me trying to do certain things.

**Comment by ZaptorZap** [comment] 2023-06-09 22:51
Duplicate of #1041

**Closed by ZaptorZap** 2023-06-09 22:51 UTC
Labels: bug
