### ISSUE TITLE
Make tetr.io extension

### ISSUE THREAD

**Issue by XxMicrowavexX** [tetrio/issues#1166] opened 2023-07-25 05:01 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

There isn't quick access for offline.

### Describe the solution you'd like

make an extension

### Describe alternatives you've considered

Using the app

**Comment by ZaptorZap** [comment] 2023-07-25 07:13
Duplicate of #521

**Closed by ZaptorZap** 2023-07-25 07:13 UTC
Labels: improvement
