### ISSUE TITLE
I keep getting lag spiked by ads every 10-15 seconds

### ISSUE THREAD

**Issue by YesNoMaybe567890** [tetrio/issues#1134] opened 2023-05-22 07:03 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

ChromeOS

### Browser and version

Version 113.0.5672.114

### Describe the bug/issue

Every 10-15 seconds, an ad loads and lag spikes my game. It was not this bad 2 days ago, and i was playing the game perfectly fine

### Reproducing

Play a game of tetris

### Expected behavior

Playing normally

**Comment by rajun274** [comment] 2023-05-23 11:34
This is likely related to https://github.com/tetrio/issues/issues/1122, which is already assigned to o5k.

**Comment by ZaptorZap** [comment] 2023-05-30 02:20
Ads in general aren't a bug, but the related issue may still be relevant. I'm closing this as a duplicate of that.

**Closed by ZaptorZap** 2023-05-30 02:20 UTC
Labels: bug
