### ISSUE TITLE
Desktop App not properly launching while in offline mode

### ISSUE THREAD

**Issue by raviohli** [tetrio/issues#761] opened 2021-09-13 15:38 UTC
- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----
When running the desktop app without internet connection or on airplane mode, the game fails to check for updates, goes to the "starting tetr.io" screen, then becomes an eternally black screen where the game never launches.
### Reproducing
1. Turn on airplane mode / disconnect from internet
2. Launch tetr.io desktop app
3. Wait for update checker failure
4. Wait for the "starting tetr.io" screen to disappear

### Expected behavior
The game should launch normally and simply not allow a login
.
### Your setup
 - **Windows 10 version 20H2 (Build 19042.1110)  **
 - **Tetr.io Desktop app

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

The app ignores all desktop commands during this time such as ctrl+shift+i and f12, so no logs are available.
After further research, it seems that the tetr.io desktop app is supposed to start 5 other processes when it is opened. As expected, 5 processes are spawned when I open the app on offline mode. After tetr.io "fails to check for updates" it appears that one process is killed and the game goes into the infinite black screen.

**Comment by ZaptorZap** [comment] 2021-09-13 22:26
This be a dupe of #521, unfortunately

**Closed by ZaptorZap** 2021-09-13 22:26 UTC
Labels: bug
