### ISSUE TITLE
out of focus from no where

### ISSUE THREAD

**Issue by joa725** [tetrio/issues#1200] opened 2023-11-09 00:45 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

ios 14.1

### Browser and version

chrome 94

### Describe the bug/issue

i was playing the game but it suddenly appears the 'out of focus' thing, and i click the screen so many times but still couldn't play the game, making my rank drop.

### Expected behavior

shouldn't happen again, cuz it is annoying

**Comment by ZaptorZap** [comment] 2023-11-09 00:49
Duplicate of #1198

**Closed by ZaptorZap** 2023-11-09 00:49 UTC
Labels: bug
