### ISSUE TITLE
Hispanic community

### ISSUE THREAD

**Issue by gugernaut** [tetrio/issues#879] opened 2022-01-25 01:35 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

The main problem is the insults in Spanish or certain idioms that are verbal aggression to others.

### Describe the solution you'd like

I will make sure that people pass me screenshots about this type of behavior and reach a conclusion, also give warnings so that they do not comment on a greater fault

### Describe alternatives you've considered

create rules for the Hispanic community, such as, respect, avoid idioms, etc etc

### Additional context

none

**Comment by ZaptorZap** [comment] 2022-01-25 01:42
The [rules](https://tetr.io/about/rules/) are absolute, and users of Hispanic origin are still subject to them. The rules may also be [translated automatically](https://tetr-io.translate.goog/about/rules/?_x_tr_sl=auto&_x_tr_tl=es&_x_tr_hl=en-US&_x_tr_pto=wapp), as they are not bound to any special webpage. Reports containing foreign(to English speakers) are translated by hand (although accuracy can vary, most of the time we use [DeepL](https://www.deepl.com/). Speaking from personal experience, this method still gets the overall point across and the reports:punishments ratio is still decently high. Furthermore, there is at least one moderator who speaks fluent Spanish)

Sorry, but this request isn't very scalable either. You'd have to make some-odd six different revisions for each of the [official languages of the UN](https://www.un.org/en/our-work/official-languages), and we just don't have that language-coverage. This request also perhaps falls into a duplicate of #102, so i'll be closing it nonetheless.

I'd like to finish this up by further suggesting: if a user in TETR.IO offends you in any form, you're always welcome to report them. We allow reporting users to include additional text reasoning during the report process, so you are also welcome to submit your own translation.

**Closed by ZaptorZap** 2022-01-25 01:42 UTC
Labels: improvement
