### ISSUE TITLE
Random game feature requests

### ISSUE THREAD

**Issue by trogfield** [tetrio/issues#629] opened 2021-02-12 11:25 UTC
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
PC during downstack excluding garbage sends 2-4 lines. Hard to code? Bad idea?

More multiplayer game modes similar to or different than current tetris game modes e.g. reverse controls, shuffled controls,

Finesse and other tetris stats showing option in custom games.

thanks for your time.

**Comment by ZaptorZap** [comment] 2022-09-09 13:37
Talking about [Color Clear](https://characters.osk.sh/#character_cc)s? That concept's been brewing for the Character System a long while now, but it's unlikely to make the transfer over to conventional battle royales.

This'd be a duplicate of issues like #77, #397, and #625.

Implemented as of [6.1.0](https://tetr.io/about/patchnotes/#chlog_6_1_0).

**Closed** 2022-09-17 00:53 UTC
Labels: improvement, user couldn't be bothered with the issue template
