### ISSUE TITLE
Swapped piece preview visibility slider option

### ISSUE THREAD

**Issue by 01yakiek** [tetrio/issues#863] opened 2021-12-30 11:49 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I'm always frustrated when my memory plays tricks on me and the swapped piece has no preview visibility slider option.

![2021-12-30_19 41 17_Thursday](https://user-images.githubusercontent.com/7377351/147749112-cf981608-57a8-4d98-9438-4b7e4a155013.png)

Look how it's barely visible. I turned up all of the sliders on gameplay but that didn't affect the swapped piece.

Edit: Swapped hold piece*

Thank you.

### Describe the solution you'd like

Add swapped piece preview visibility.

### Describe alternatives you've considered

I can simply refrain from playing the game. I'm new to Tetr.io and I'm sure my exit means nothing to the game. Do what you will.

**Comment by godotgamedeveloper** [comment] 2022-08-16 13:13
@ZaptorZap Just so happened to come across this one from issue browsing.  You may want to mark this one as a duplicate of existing issues https://github.com/tetrio/issues/issues/999 and https://github.com/tetrio/issues/issues/76.  Cheers.

**Comment by ZaptorZap** [comment] 2022-08-16 13:15
Seconded

**Closed by ZaptorZap** 2022-08-16 13:15 UTC
Labels: improvement, feat: ui

**Comment by ZaptorZap** [comment] 2022-08-16 13:16
Although—I'd like to mention this was created during [the Holiday reskin](https://tetris.wiki/TETR.IO#Holidays), and the screenshot features zero background elements at all, so the effect here was very overpronounced. Nowadays, the skin has changed back to what it was a while back, which is _marginally_ more noticable.
