### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by starbos** [tetrio/issues#559] opened 2020-12-16 00:13 UTC
### Checklist (issue will be disregarded & closed if incomplete!)

- [*] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [*] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
- [*] I am using a **supported browser** or the Desktop Client.
- [*] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [*] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
After not opening TETR.IO for most of the day, I randomly had stutters while playing other games. When looking at Task Manager, I saw TETR.IO using 11GB of ram without even being open. Uninstalling and reinstalling fixed the issue. I have no way to reproduce this yet, but I believe it's still something to look into.

### Reproducing
unknown method to reproduce

### Expected behavior
TETR.IO using way more memory than expected

### Screenshots
none

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Most recent TETR.IO desktop client

### Additional context
I'm sorry that I don't know of any method to reproduce this issue. I was going to reach out through Discord as it didn't seem super common, but was directed here. I hope you still read this.

**Comment by o5k** [comment] 2020-12-16 00:18
Duplicate of #545 , hopefulyl fixed in next version

**Closed by o5k** 2020-12-16 00:18 UTC
Labels: bug
