### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by Randomguythe1st** [tetrio/issues#1155] opened 2023-06-26 01:37 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 114

### Describe the bug/issue

I have not logged into tetr.io in a long time and have forgotten my password. The password I used with my password manager did not work (likely because I changed my password on a different device I do not have access to anymore). I pressed the "I forgot" button and followed the instructions yet I did not get an Email after a long time. I have tried multiple times but no matter what I do it will not send the email to me. I am 100% confident I typed every possible password I remember correctly, and I have checked my Junk mail, and Email multiple times. I also know I can receive emails in the first place because I have received recently after my attempts to reset my password. I understand if you cannot fix this issue if it is the fault of the browser instead of the website itself. 

### Reproducing

1.Log out of your tetr.io account if you have not already
2.type your username and get to the password prompt
3.click "I forgot"
4. enter in your email and clear the captcha
5. check your email, for me it says at the bottom "checking for mail" and then says "updated just now" even though nothing happened

### Expected behavior

I expected to receive an Email to reset my password.

### Console logs

![Screenshot (32)](https://github.com/tetrio/issues/assets/137737834/f80b2c9f-0dda-407b-8bde-1d4f0eacf454)

**Comment by Randomguythe1st** [comment] 2023-06-26 01:39
I think I forgot to include another screenshot of the console logs here:

**Comment by Randomguythe1st** [comment] 2023-06-26 01:39
wait shot I did not mean to send that

**Comment by Randomguythe1st** [comment] 2023-06-26 01:40
![Screenshot (31)](https://github.com/tetrio/issues/assets/137737834/e3b708e5-a205-4042-9742-351e004281c4)

**Comment by ZaptorZap** [comment] 2023-06-26 01:59
While I can confirm that the password reset function works perfectly fine for me, the `403 FORBIDDEN` responses in the console are a bit worrying. Those can be normally output as part of a genuine reset attempt, as `403` seems to make the captcha prompt appear. 

Since the reset mechanism works A-OK for me I'm closing this as a potentially misplaced account support issue—where you may simply be inputting the wrong email address. You may want to email `support@tetr.io` for further help, as we're unwilling to provide account support over this public repository.

**Closed by ZaptorZap** 2023-06-26 01:59 UTC
Labels: bug

**Comment by Randomguythe1st** [comment] 2023-06-26 21:14
I tinkered with my settings in hopes that it would send the email, I have additional screenshots that may help, the main problem I believe stems from this "Failed to load resource: server" error message or the error shown in the screenshot below
![Screenshot (42)](https://github.com/tetrio/issues/assets/137737834/d4a141c7-4fe2-493c-b92b-2b82d2cf20d9)
