### ISSUE TITLE
Piece automatically moves to one side and screen shows out of focus.

### ISSUE THREAD

**Issue by phosph0rite** [tetrio/issues#872] opened 2022-01-10 20:23 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 96

### Describe the bug/issue

When playing tetra league the out-of-focus thing popped up and told me to click to return to tetrio. when I started playing the piece automatically moved to the side. I topped out and then the next match started the same thing happened again. I played a few more matches and restarted my computer and it happened again! Also played different game modes like 40 lines, blitz, and custom game and it still happened. Please fix. 

### Reproducing

I don't know how to reproduce.

### Expected behavior

Pieces don't move to the side automatically.

### Screenshots

![image](https://user-images.githubusercontent.com/97476654/148833630-9f6aa0be-0141-46d9-a133-326188967856.png)\

![image](https://user-images.githubusercontent.com/97476654/148834320-e54db100-0c18-4b10-a67a-c0b7ee25e7e7.png)

**Comment by ZaptorZap** [comment] 2022-01-10 20:37
This seems to be a duplicate of #680, sorry.

**Closed by ZaptorZap** 2022-01-10 20:37 UTC
Labels: bug
