### ISSUE TITLE
Laggy and stuttering audio even with lowest graphic settings

### ISSUE THREAD

**Issue by timelessnesses** [tetrio/issues#940] opened 2022-05-09 09:50 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

TETR.IO application

### Describe the bug/issue

Audio will become laggy and stuttering randomly (most likely happens on multiplayer match).  
This also can be happened if there's lots of audio need to be played like multiple t spins etc.

### Reproducing

1. Play tetr.io with quick lobby or any room 
2. listen to the sound when you try comboing or doing multiple t spins or quad or whatever it is

### Expected behavior

Audio shouldn't be laggy and stuttered

### Screenshots

None

### Console logs

![image](https://user-images.githubusercontent.com/59832159/167385407-a26ddfab-d87b-436c-b3a9-03235acab219.png)
![image](https://user-images.githubusercontent.com/59832159/167385469-54fe3518-c4ac-4ab4-ac33-82a005f9e8c8.png)

**Comment by ZaptorZap** [comment] 2022-05-09 21:36
This seems to be a duplicate of #244, an issue put to rest a long while ago. I don't really intend to reopen it due to concerns over this being an OS wide issue, although I will mention these instructions personally solved any crackling audio I've had back then:
![image](https://user-images.githubusercontent.com/64891705/167502422-899fd987-65c4-44fb-977c-ab8d6fae7798.png)

I'll mention you don't necessarily have to make this the absolute lowest option—it's just that I personally don't recognize any difference when I do. (I've never been an audiophile…)

**Closed by ZaptorZap** 2022-05-09 21:36 UTC
Labels: bug
