### ISSUE TITLE
Display some sort of timestamp next to messages in the chat

### ISSUE THREAD

**Issue by Speedphoenix** [tetrio/issues#1189] opened 2023-10-15 20:50 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

When playing heated tetra league matches, I sometimes get individual rounds that I want to rewatch later in the replay (usually I played particularly well, or the opponent did something I didn't understand).  
I generally send messages in chat when that happens.

At the end of the game, I need to remember which round that was, and if I had forgotten I potentially have 15 rounds to look through to find what I'm looking for.

And unfortunately the messages in chat don't tell me when they were sent.

![image](https://github.com/tetrio/issues/assets/22801009/5d5121bf-bdb8-431d-86ec-d5020debbbd2)
![image](https://github.com/tetrio/issues/assets/22801009/b45e9d62-63bd-4706-896e-ee7632badc94)

### Describe the solution you'd like

The messages would display the time they were sent at (either relative to the start of the room, or in your timezone), and/or the round that just ended

something like this (edited in paint)
![image](https://github.com/tetrio/issues/assets/22801009/a54b7463-8db4-4f2a-9153-c0ca2bdfad21)

### Describe alternatives you've considered

- Manualy writing down the game number on the side when the memorable thing happens, but that requires unfocusing the tetr.io window or grabbing physical tools, possibly breaking your focus for the next round that's about to start
- An in-game marker you would bind on a particular hotkey, that would later show up next to the round on the replay screen, and possibly even on the replay timeline together with finesse faults

**Comment by ZaptorZap** [comment] 2023-10-16 00:56
Duplicate of #597

**Closed by ZaptorZap** 2023-10-16 00:56 UTC
Labels: improvement
