### ISSUE TITLE
Zen B2B sound glitch

### ISSUE THREAD

**Issue by patty-boi** [tetrio/issues#1026] opened 2022-10-13 03:29 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10, Version 21H2

### Browser and version

I use desktop tetr.io

### Describe the bug/issue

On Zen, if you get a b2b of 3 or higher, then die/reset and clear a line, and you will hear the sound when you stop your b2b

### Reproducing

1. go into zen
2. get b2b of 3 or higher
3. die or reset
4. clear a line
5. sound

### Expected behavior

No b2b sound

### Screenshots

https://user-images.githubusercontent.com/115676852/195491909-40fda781-d477-431e-a05b-c260c4a8e6d0.mp4

**Comment by ZaptorZap** [comment] 2022-10-13 03:32
Seems to be a duplicate of #450, sorry about that.

**Closed by ZaptorZap** 2022-10-13 03:32 UTC
Labels: bug

**Comment by patty-boi** [comment] 2022-10-13 03:37
Ah ok. I thought that one was something else when looking. Thanks!

**Comment by ZaptorZap** [comment] 2022-10-13 03:38
It's admittedly a bit nuanced/unclear, but I'd group the issues together personally. doktorocelot's reply specifically noting the same issue with levelups really makes me suspicious of the logic tying into itself here.
