### ISSUE TITLE
language

### ISSUE THREAD

**Issue by panda-pazoo** [tetrio/issues#1100] opened 2023-04-01 15:50 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I hope can add the choose language in the set up.It's so important to me,Because when I download window I find I don't understand some word,it's to me has some hard to play the game.

### Describe the solution you'd like

add chinese

### Describe alternatives you've considered

ON

### Additional context

NO

**Comment by ZaptorZap** [comment] 2023-04-01 15:52
Duplicate of #102

**Closed by ZaptorZap** 2023-04-01 15:52 UTC
Labels: improvement
