### ISSUE TITLE
Random advertisements popping up mid game

### ISSUE THREAD

**Issue by tabik0** [tetrio/issues#1140] opened 2023-05-30 02:18 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Uncertain

### Describe the bug/issue

Advertisements randomly popping up and covering parts of the screen while in Tetra League.

### Reproducing

1.  Multiplayer
2.  Tetra League 
3.  Enter Game
4.  Ad randomly occurs during gameplay

### Expected behavior

Different formats of advertisements popping up, happened to me twice, one of which was blocking me from seeing my side and I couldn't play

### Screenshots

![image](https://github.com/tetrio/issues/assets/130521502/8c30552e-46bd-42ae-ac63-fdd1dfe72e1a)

### Console logs

![image](https://github.com/tetrio/issues/assets/130521502/946234a5-14c9-425f-9e5e-e51ebda982f9)

**Comment by ZaptorZap** [comment] 2023-05-30 02:20
Duplicate of #1122

**Closed by ZaptorZap** 2023-05-30 02:20 UTC
Labels: bug
