### ISSUE TITLE
Remove "Get TETR.IO Desktop" when in Desktop app

### ISSUE THREAD

**Issue by tilda** [tetrio/issues#420] opened 2020-07-10 04:57 UTC
### Is your feature request related to a problem? Please describe.
No problem really, just a little bit weird to me

### Describe the solution you'd like
The download icon should not appear when the desktop client is detected

### Describe alternatives you've considered
N/A

### Additional context
![image](https://user-images.githubusercontent.com/8301262/87118020-d6c22f80-c23f-11ea-890e-77b15c1e89e8.png)

**Comment by o5k** [comment] 2020-07-10 12:13
Duplicate of #337

**Closed by o5k** 2020-07-10 12:13 UTC
Labels: improvement
