### ISSUE TITLE
Custom music for Private matches

### ISSUE THREAD

**Issue by USSRRED** [tetrio/issues#894] opened 2022-02-24 00:01 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Not a problem, but It'd be cool to have it.

### Describe the solution you'd like

Being able to upload music files and them playing ingame. (The music would loop after a while if the game has not ended yet)

### Describe alternatives you've considered

N/A

### Additional context

Maybe like a fade out effect on the music when the match is over.
![2022-02-23-18-03-tetr io](https://user-images.githubusercontent.com/100323041/155431599-39ef0e40-47d2-4e5f-aa79-d50d0b24e9f7.png)

**Comment by o5k** [comment] 2022-02-24 00:10
Duplicate of #187

**Closed by o5k** 2022-02-24 00:10 UTC
Labels: improvement

**Comment by USSRRED** [comment] 2022-02-24 03:36
> Duplicate of #187

Yes, but they mean as in only they can hear it. My idea is that everyone in the match can hear it.

**Comment by ZaptorZap** [comment] 2022-02-24 03:38
Feel free to suggest this request in that issue _none-the-less;_ it's still extremely related. Thank you.
