### ISSUE TITLE
Allow lock delay decreasing

### ISSUE THREAD

**Issue by GamerOn117** [tetrio/issues#1194] opened 2023-10-28 03:19 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

When I want to play against others in 20G, I can't simulate harder levels by decreasing lock delay over time.

### Describe the solution you'd like

What if we were to add a new option that sets how fast the lock delay decreases once the gravity tries to go above 20G? Basically, when the gravity is at 20G and the game tries to make it go faster, it'll instead take off a certain number (can be a decimal) of lock delay frames every second.

### Describe alternatives you've considered

You could also potentially bind the lock delay to the gravity where if the gravity is, say, 21G, it'll have one less frame of lock delay

**Comment by ZaptorZap** [comment] 2023-10-29 10:49
Duplicate of #1000

It's likely this'll be implemented when #456 is implemented.

**Closed by ZaptorZap** 2023-10-29 10:49 UTC
Labels: improvement
