### ISSUE TITLE
Piece Duplication

### ISSUE THREAD

**Issue by orangetriangle** [tetrio/issues#865] opened 2022-01-05 18:55 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 96

### Describe the bug/issue

In some scenarios, a piece can be placed twice -- once where it should be, and once below that, embedded within the garbage.

### Reproducing

1. Drag this replay into TETR.IO [surelythisisaglitch.zip](https://github.com/tetrio/issues/files/7817104/surelythisisaglitch.zip)
2. Observe the glitch occurring at time 0:43.050 (frame 2582)
 

### Expected behavior

The J piece should be placed only once, at the top of the stack.

### Screenshots

![image](https://user-images.githubusercontent.com/77557642/148272580-c0217e8f-7847-484e-9674-ec0dfcfe987b.png)

### Additional context

I had the extensions AdBlock, Grammarly, and uBlock Origin active when this glitch occurred in the actual game.

**Comment by ZaptorZap** [comment] 2022-04-08 22:08
I'm very sure this is caused by running out of lock delays, of which you have fifteen.
![image](https://user-images.githubusercontent.com/64891705/162534147-b4183a10-1c45-4b07-bb10-69beb1ed90ff.png)
This is pretty much a globally set limit, so that's nothing new. Running out of lock delays and getting your piece forced down on the same movement garbage enters the field with causes the issue. Here's an illustration of how many lock delays you had in that replay:

https://user-images.githubusercontent.com/64891705/162538245-361f6318-2bb5-4cc5-8ef8-5a420c0a9e74.mp4

Note that your last movement here was **not** manually requesting a hard drop or anything of the sort, you simply used another lock reset when none were available. It's for this reason I believe this glitch could *potentially* be abusable in a ranked setting, allowing pieces to "deep drop" into areas they shouldn't be in, but doing so at a high level consistently sounds absurd and unlikely.

**Comment by o5k** [comment] 2022-05-22 19:14
Seems it's calling the lock-in code twice, you can also see your I-piece in next getting skipped

**Comment by o5k** [comment] 2022-05-22 19:20
Found the issue; you tripped the out-of-lock-reset locker **and** the out-of-lock-time locker at the same exact moment. A very rare occurence

Important to fix too... in normal cases this would actually cause an instant top-out (it'd lock one piece in the normal position, then the next piece right in the spawn position), while in this case (where ARE is enabled) it just duplicates the piece - once in normal position, then once again in the original position it was meant to be, skipping one off the Next queue

It's fixed in the next patch.

**Closed by o5k** 2022-05-22 19:20 UTC
Labels: bug, feat: engine

**Comment by orangetriangle** [comment] 2022-05-27 23:34
(Well, trying the replay again now gives a desync, but I suppose that's not something that can be helped without unnecessarily complicating the TETR.IO source code :p)
