### ISSUE TITLE
4W Bug

### ISSUE THREAD

**Issue by nocnoc2** [tetrio/issues#1178] opened 2023-08-31 08:33 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 116

### Describe the bug/issue

I have a problem when I custom a game in 4W mode and it's a bug. My screen is 4W mode, but my opponent's is default mode

### Expected behavior

I need you guys to fix it. please. =(((((

### Screenshots

![Capture](https://github.com/tetrio/issues/assets/143697744/2a502e89-ac1a-4f66-8cc3-62c52c68d595)
![Capture1](https://github.com/tetrio/issues/assets/143697744/d5ef544c-6850-44d3-8fba-4940eef33237)

**Comment by ZaptorZap** [comment] 2023-08-31 08:35
Duplicate of #1176

**Closed by ZaptorZap** 2023-08-31 08:35 UTC
Labels: bug

**Comment by nocnoc2** [comment] 2023-08-31 10:25
Finally, will you guys fix it for me????
