### ISSUE TITLE
I was logged out and can't log back in

### ISSUE THREAD

**Issue by daazuhn** [tetrio/issues#423] opened 2020-07-10 16:00 UTC
### Describe the bug/issue
When I opened tetrio desktop, it logged me out even though I have my setting on always skip login. When I tried to login, it would say that I was logged out and that I had to log back in. I've already tried deleting it and redownloading it, but it said the same thing again. Although when I log in using a browser it goes in just fine. Going back onto the desktop version after logging in on a browser doesn't change anything though. Still can't get on

### Reproducing
1. Tetrio shuts down or restarts by itself
2. Try to log back on
3. at the bottom right corner of the screen it says that I have been logged out and should log back in

### Expected behavior
I put in my password and am able to get back into tetrio

### Screenshots
![Screen Shot 2020-07-10 at 11 53 13 AM](https://user-images.githubusercontent.com/68092469/87174058-a3fe5280-c2a4-11ea-84f6-ad26cb308e57.png)

### Your setup
 - **OS and version**: [e.g. Windows 7]
macOS Mojave 10.14.6
 - **Browser and version**: [e.g. Chrome 76]
most recent version of tetrio desktop because I downloaded it again

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment] 2020-07-10 16:01
DUplicate of #415, press F5

**Closed by o5k** 2020-07-10 16:01 UTC
Labels: bug
