### ISSUE TITLE
Opponent's board is not properly shown resulting in false top out for the opponent in Tetra League

### ISSUE THREAD

**Issue by sambelgore** [tetrio/issues#616] opened 2021-02-03 08:36 UTC
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
This only happened once when I'm (SPICYCHICKEN) matched against a player named KAMOTO.

At the early game, my client shows that KAMOTO is placing their pieces erratically until they tops out, but the game does not proceed to move to the next round until I ko'd by topping out from their attacks, it happens consistently throughout the set.

During that time, I can still play and receive garbage, indicating KAMOTO is still playing and my client doesn't know it

after the game, I watched the replay, showing that their board is showing just fine, Another issue I found is that, they doesn't receive any garbage, but sometimes their board would accept garbage at the very early game.

A player named QUINTY also happened to be matched against KAMOTO in Tetra League right after my match, and QUINTY also experienced the same issue, except when they matched again for the third time, the issue does not occur.

I suspect that it's an issue within KAMOTO's client side.

I apologize if my bug description might not be clear (English is not my native language nor I'm fluent at it, but I'm trying my best to explain)

### Reproducing
I'm not sure if it is reproduceable, but you can try matching against KAMOTO on Tetra League

### Expected behavior
A normal Tetra League match where we could exchange attacks and be able to see Opponent's board

### Screenshots
(my attacks got no particle effect, and his attack seems to be coming from above)
![Screenshot_392](https://user-images.githubusercontent.com/56397456/106719424-def71780-6634-11eb-950c-dcce48ff6de9.png)
![Screenshot_393](https://user-images.githubusercontent.com/56397456/106719432-e1597180-6634-11eb-88e3-8534165bd77e.png)
![Screenshot_394](https://user-images.githubusercontent.com/56397456/106719436-e28a9e80-6634-11eb-9abe-741100e1e07b.png)

### Your setup
 - **OS and version**: [Windows 10 2004]
 - **Browser and version**: Tetr.io desktop client

**Comment by 42triangles** [comment] 2021-02-05 04:26
I actually encountered this issue too, but I was on the other end. This happened in a match MEEEPMEERP (my nickname in tetr.io is the same as here, 42triangles), in which they asked me if I was hacking or anything of the sort, and that they had it on video. So I asked them for the video, knowing that I didn't cheat, and it looks similar to these screenshots, except that my movements weren't reduced like here but probably amplified (it's hard to tell).

I won't try to reproduce this (since not seeing the board of the other player is an unfair disadvantage), but what I suspect was the issue is that I entered matchmaking and then went back to the settings to change the handling settings a bit. In fact I was still holding onto the handle of the DAS slider while the game started, if I recall correctly.

I suspect that it maybe sends the settings before they are changed on my client, and to replay everything it sends the inputs and not game states to the other player, and can't replay it correctly because of that or something of the sort.

**Comment by deedeeen** [comment] 2021-02-23 00:27
> I actually encountered this issue too, but I was on the other end. This happened in a match MEEEPMEERP (my nickname in tetr.io is the same as here, 42triangles), in which they asked me if I was hacking or anything of the sort, and that they had it on video. So I asked them for the video, knowing that I didn't cheat, and it looks similar to these screenshots, except that my movements weren't reduced like here but probably amplified (it's hard to tell).
> 
> I won't try to reproduce this (since not seeing the board of the other player is an unfair disadvantage), but what I suspect was the issue is that I entered matchmaking and then went back to the settings to change the handling settings a bit. In fact I was still holding onto the handle of the DAS slider while the game started, if I recall correctly.
> 
> I suspect that it maybe sends the settings before they are changed on my client, and to replay everything it sends the inputs and not game states to the other player, and can't replay it correctly because of that or something of the sort.
> 
> Here's the video they sent me:
> 
>  Tetrio.mp4

Wait, you _can_ alter your handling when in matchmaking? I thought that it was disabled a few months ago.

**Comment by o5k** [comment] 2021-02-23 01:52
> I thought that it was disabled a few months ago.

It was reenabled in the 6.0.0 update. This issue should be completely fixed now, not sure why this issue was still open (a duplicate?)

If it's not, let me know

**Closed by o5k** 2021-02-23 01:52 UTC
Labels: bug
