### ISSUE TITLE
An in-game bug that moves tetrominos to the right.

### ISSUE THREAD

**Issue by Vo1d3nIsNotHere** [tetrio/issues#1153] opened 2023-06-14 20:48 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

HP Chromebook Version 113.0.5672.134 (Official Build) (64-bit) 

### Browser and version

Version 113.0.5672.134 (Official Build) (64-bit) (it says for both)

### Describe the bug/issue

Sometimes, whenever I play some matches and the game goes out of focus, the pieces always move to the right. Whenever I try to move it, it always goes back to the right of the board. It goes away whenever I start spamming the space bar.

### Reproducing

It doesn't happen often, (like I sad above) but it mainly happens during matches (rooms, tetra league, etc.), so there's no way to replicate it. I saved a TETRA LEAGUE game so you can see. The game has to go out of focus randomly to happen.

Link: https://tetr.io/#R:zN9yeceYn

Start at 0:15.900

### Expected behavior

I don't know how to explain this part to be honest.

**Comment by ZaptorZap** [comment] 2023-06-15 04:30
Duplicate of #123

**Closed by ZaptorZap** 2023-06-15 04:30 UTC
Labels: bug
