### ISSUE TITLE
Suppression of Super Lobby notifications & scroll-pausing

### ISSUE THREAD

**Issue by deedeeen** [tetrio/issues#780] opened 2021-10-02 13:51 UTC
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
Sometimes rooms can have fluctuating players around the count of 100 (for example, Quick Play), and the notification of Super Lobby Mode engagement (and its disengagement) can appear multiple times, causing disruptions in reading messages. In regards to this matter, when you try to scroll up to read a room messages history, a new message will cause you to fall down to the bottom completely.

### Describe the solution you'd like
• SB suppression: do not show any (dis)engagements within 30 seconds since the last shown engagement notification
• Scroll-pause: do not automatically de-scroll for a new message (optional: add a "new messages" notification)

### Describe alternatives you've considered
• SB suppression: put emphasis on the player count instead of notifying (example: coloring it red)
• Scroll-pause: no alternatives considered yet

**Comment by ZaptorZap** [comment] 2022-05-20 23:52
This issue appears to be a duplicate of both #644 and #165, sorry about that.

**Closed by ZaptorZap** 2022-05-20 23:52 UTC
Labels: improvement

**Comment by deedeeen** [comment] 2022-08-17 11:11
I just realized that the notification of SB is not a strict duplication of #644, as the joining and leaving notifications are different from the notifications of (dis)engagement for SB, and fixing one will not help the other.

**Comment by o5k** [comment] 2022-08-17 12:27
wasted GET...

**Comment by deedeeen** [comment] 2022-08-18 02:48
never stale :p
