### ISSUE TITLE
The letters overlap when you get perfect clear at the same time as level complete in ZEN mode.

### ISSUE THREAD

**Issue by kaaifn** [tetrio/issues#1209] opened 2023-11-18 07:09 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Desktop

### Describe the bug/issue

When I do perfect clear and level clear at the same time in solo zen mode, the letters overlap. I know this is a small bug, but please fix it!

### Expected behavior

The letters are in the same position, so they are covered.

**Comment by ZaptorZap** [comment] 2023-11-28 03:14
Duplicate of #720

**Closed by ZaptorZap** 2023-11-28 03:14 UTC
Labels: bug
