### ISSUE TITLE
Add an option to stop the chat scrolling

### ISSUE THREAD

**Issue by joohyonbae** [tetrio/issues#945] opened 2022-05-20 13:03 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

If I scroll up to read an old message, it sends back me to the bottom whenever there is a new message.

### Describe the solution you'd like

There should be an option to stop the chat scrolling automatically when hovering over it.

### Describe alternatives you've considered

An option to entirely stop the chat scrolling automatically.

### Additional context

The chat automatically scrolls to the bottom when there is a new message. It can be hard to read the chat when there are many people messaging.

**Comment by deedeeen** [comment] 2022-05-20 15:31
I have already suggested this in #780.

**Comment by ZaptorZap** [comment] 2022-05-20 23:51
Come to think of it, that's also a duplicate of #165. Sorry.

**Closed by ZaptorZap** 2022-05-20 23:51 UTC
Labels: improvement
