### ISSUE TITLE
One click to ZEN mode while waiting for tetra league matchmaking

### ISSUE THREAD

**Issue by sufyandaredevil** [tetrio/issues#1037] opened 2022-10-29 17:39 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

When waiting for matchmaking I just want to get into zen mode as quick as possible for a quick solve

### Describe the solution you'd like

A simple button click

### Describe alternatives you've considered

a keyboard shortcut would be better

**Comment by ZaptorZap** [comment] 2022-10-29 17:42
Duplicate of #711

**Closed by ZaptorZap** 2022-10-29 17:42 UTC
Labels: improvement
