### ISSUE TITLE
Improvement graph

### ISSUE THREAD

**Issue by WillTRM** [tetrio/issues#902] opened 2022-03-08 19:27 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

One of my favorite features on jstris was the improvement graph because it showed my skill progression. However on this site, there simply isn't a graph

### Describe the solution you'd like

I would like an option under player scores to toggle a graph that shows blitz score, 40L time, and TR over time.

### Describe alternatives you've considered

There are no potential alternatives to a graph.

### Additional context

![image](https://user-images.githubusercontent.com/92384657/157310614-666b0964-a610-4ef7-8515-1ee140f8d868.png)
It could look something like this

**Comment by Chr1s28** [comment] 2022-04-03 14:23
I also would be interested in something like this. I haven't found anything in the API that could be used to get the data, and you can only see the top 10 best runs. What I did find was that everytime you finish for example a 40l run it gets sent to the server (https://tetr.io/api/games/submit), so they probably have the data somewhere. I'm gonna search around to maybe find an endpoint to get that data.

**Comment by ZaptorZap** [comment] 2022-04-03 22:51
Well @Chr1s28, you might be interested in the [news](https://tetr.io/about/api/#newsstream) and the [`any_userrecent_`](https://tetr.io/about/api/#streamid) [replay stream](https://tetr.io/about/api/#streamsstream) endpoints. Notably, these endpoints are **not** from the main game API, something direct usage of from a user account is **strictly forbidden** of. I surely hope you haven't been reverse engineering the main game API, especially when [a very documented, public API](https://tetr.io/about/api) for [the TETRA CHANNEL site](https://ch.tetr.io/) exists.

That said, the `any_userrecent_` endpoint would need to be grabbed a lot to catch every run, so you certainly couldn't apply them to the userbase at large. Grabbing everyone's news as it occurs through the global news stream could be viable, but you couldn't catch the runs that weren't personal bests, in that case. In my opinion, the most viable usage would be through an opt-in process, similar to that of TETR.IO Discord user CCRed95#6710's pending "tetriostats.com" project, one that I believe plans to do this eventually. Of course, providing the functionality in a third party site wouldn't officially solve the problem here, otherwise #359 would've been closed a looooong time ago, but it would alleviate it.

**Comment by Chr1s28** [comment] 2022-04-06 08:48
No no, I would never try to reverse engineer the game API of course :). I looked at the TCH API but must have missed those endpoints. Thanks for the help.

**Comment by ZaptorZap** [comment] 2022-09-09 10:53
Oh, whoops. This is a duplicate of #830.

**Closed by ZaptorZap** 2022-09-09 10:53 UTC
Labels: improvement, feat: channel
