### ISSUE TITLE
You dont get the end screen if u ko ur oponent and they disconnect

### ISSUE THREAD

**Issue by Yoreni** [tetrio/issues#930] opened 2022-04-20 08:20 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Google chrome Version 100.0.4896.88

### Describe the bug/issue

when ur oponent disconnect the game doesnt make the match end so u still see ur board and can play on it. when u ko urself u can only see the points hud and the chat hud.

### Reproducing

1. go in to a tl match
2. make it so its a tiebreaker (maybe match point for you atleast)
3. ko ur oponent
4. then the oponent disconnect at the right time
5. u wont get ur point and this bug will happen

### Expected behavior

i get my final point and the rating changes

### Screenshots

![image](https://user-images.githubusercontent.com/30157855/164183528-8af1cd29-3e41-4fad-86cd-c57549f0ccab.png)
i recoded my pov so the image is from the recording. i didnt take any screenshots during

**Comment by ZaptorZap** [comment] 2022-04-20 08:22
This is a duplicate of #888, which just recently cleared itself up.

**Closed by ZaptorZap** 2022-04-20 08:22 UTC
Labels: bug
