### ISSUE TITLE
holding multiple pieces at a time on 2 minute blitz

### ISSUE THREAD

**Issue by Bannana-person** [tetrio/issues#1147] opened 2023-06-07 22:00 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Chrome OS 112.0.5615.134

### Browser and version

Google Chrome Version 112.0.5615.134

### Describe the bug/issue

if you go to 2 minute blitz, finish the 2 minutes and before it loads the score page press "R" then you can hold multiple pieces at a time

### Reproducing

go to 2 minute blitz
finish the 2 minutes 
and before it loads the score page press "R"
then you can hold multiple pieces at a time

### Expected behavior

to only be able to hold one piece at a time

**Comment by ZaptorZap** [comment] 2023-06-07 23:04
I can't get this to happen and I've feverishly mashed `R` to restart before the results showed up since the beginning. Do you have a video? I would also wager that you're not holding several pieces in one board, but instead, holding once as expected in two. (duplicate board bugs have existed, where one board is under the other, but they're rare and again, I've never experienced issues by retrying in this fashion.)

**Comment by ZaptorZap** [comment] 2023-06-21 02:58
Closing due to reproduction/confirmation issues.

**Closed by ZaptorZap** 2023-06-21 02:58 UTC
Labels: bug, feat: solo, cannot reproduce
