### ISSUE TITLE
Game start is always attributed to [SYS] regardless of who started

### ISSUE THREAD

**Issue by deep4amthoughts** [tetrio/issues#1128] opened 2023-04-30 08:26 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

TETR.IO Desktop, v6.3.3

### Describe the bug/issue

When starting a game, the chat reports `[SYS] started the game` even if the game was not automatically started by the system.

### Reproducing

• Join any room, public or private.
• Have a user manually start the game, either with the `START` button or by using `/start` in the ingame chat.

### Expected behavior

The chat should correctly reference the user who started the game.

### Screenshots

https://user-images.githubusercontent.com/92073446/235343365-b777e4e4-11a4-43c4-9fae-75c8ead8e77a.mp4

**Comment by deep4amthoughts** [comment] 2023-05-01 04:13
It appears the same bug holds true for the abort message, shown here:
https://user-images.githubusercontent.com/92073446/235405338-94aae2c2-1a32-4467-9591-079ec2dde7e0.mp4
Unrelated strange behavior at the end of the clip — the UI implies I'm in the spectator bracket, but I'm still able to start games as normal and play in them. However, this causes the spectate/play button on the bottom left to **stop working** (that is, I'm stuck in the players bracket) until I use the chat command `/spec`, at which point I'm moved to the spectator bracket and can use the button or chat commands again with the expected outcomes. Probably not worth opening another issue for, but I'm noting it here.

**Comment by Dimentio** [comment] 2023-05-01 14:20
Fixed in next update, as for the unrelated strange behavior I can't reproduce if you manage to find a way to reproduce easily make a new issue!

**Closed by Dimentio** 2023-05-01 14:20 UTC
Labels: bug, feat: ui
