### ISSUE TITLE
Log in error with desktop client

### ISSUE THREAD

**Issue by Tohny123** [tetrio/issues#416] opened 2020-07-10 00:04 UTC
### Describe the bug/issue
When I log in with desktop client I get a "You were logged out, please log in again" error
This error doesn't happen with the website
### Reproducing
1. Go to the tetr.io desktop client
2. Type in username into the box provided
3. Confirm username and type password

### Expected behavior
I should normally be at the main menu of tetr.io
### Your setup
 - **OS and version**: 
Windows 10 2004
 - **Browser and version**: 
Chrome 83 (worked)
### Additional context
Error message:
![Annotation 2020-07-09 200342](https://user-images.githubusercontent.com/68088010/87102249-4e339700-c21f-11ea-9284-3cd20b11188b.png)

**Comment by Tohny123** [comment] 2020-07-10 00:06
Reinstalling the program fixes this issue

**Comment by ZmanAce** [comment] 2020-07-10 06:25
Tohny123 I went into the issue and found out a manual fix! Check my bug report to see how

**Comment by o5k** [comment] 2020-07-10 12:12
DUplicate of #415 - hit F5 on this screen to fix the issue

**Closed by o5k** 2020-07-10 12:12 UTC
Labels: bug
