### ISSUE TITLE
180  spin Glitches

### ISSUE THREAD

**Issue by VeryEBadAtCoding** [tetrio/issues#1186] opened 2023-10-04 22:38 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

 Chromebook

### Browser and version

Chrome (newest version)

### Describe the bug/issue

While messing around with 180's, I realized that with most pieces when you used 180 and it looks the sam as before, It would move up on space and sometimes even trigger a spin.

### Reproducing

1. Go on any gamemode (Zen was where I first noticed it)
2. Take any piece, I and Z are the glitchiest for example
3. Press 180 and the piece moves up, and if in between certain blocks it will spin

### Expected behavior

I expected the piece to just do a 180 in midair, but instead it ended up moving up allowing a even slower fall time and a z spin for me on nothing, this was tested in Zen, I will test more (username is Axotea)

### Additional context

Just want to make sure this was taken care of, or intended, but it is very powerful

**Comment by ZaptorZap** [comment] 2023-10-04 22:46
Duplicate of #1185(awaiting actual proof)? You'll notice you can only climb one row with 180s, and you can do the same with benign clockwise and counter-clockwise rotations as well. This is **intentional**, it's a side effect of designed piece asymmetry with the [Super Rotation System](https://tetris.wiki/Super_Rotation_System). You'll notice you cannot stall a piece forever under any conditions in an online room if you think this is abusable—the piece **will** fall a row, even under `0` gravity, at some point. This is due to built-in antistall mechanics.

**Comment by ZaptorZap** [comment] 2023-10-06 02:08
Closing due to assumed unfamiliarity with game mechanics.

**Closed by ZaptorZap** 2023-10-06 02:08 UTC
Labels: bug, needs-info
