### ISSUE TITLE
Overlayed Ads

### ISSUE THREAD

**Issue by chifuuxx** [tetrio/issues#1148] opened 2023-06-08 15:40 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Google Chrome OS, Version 113.0.5672.134 (Official Build) (64-bit)

### Browser and version

Google, Version 113.0.5672.134 (Official Build) (64-bit)

### Describe the bug/issue

When playing ingame, (Tetra League and lobbies), ads will appear at the bottom of the screen while I am playing. The ads will stack up to 1-4 different ads and will cover up the bottom of the tetris board, making me unable to see it. I have lost many Tetra League battles sadly because of this. 

### Reproducing

1. Login to Tetrio
2. Go into a Multiplayer game
3. Enter the Tetris Board
4. Ads will popup at bottom

### Expected behavior

I expected that the ads would be overlayed by the board, but it appears to not. Instead they would cover up the board and block the player's view.

**Comment by ZudoB** [comment] 2023-06-08 16:12
Duplicate of #1122, we're working with our ad network to resolve this.

**Closed by ZudoB** 2023-06-08 16:12 UTC
Labels: bug
