### ISSUE TITLE
Set Board Width&Height in rooms

### ISSUE THREAD

**Issue by JadiPlayz** [tetrio/issues#1047] opened 2022-11-18 08:56 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I'm always frustraded when you cannot set board width&height In rooms

### Describe the solution you'd like

Setting Board Width&height in rooms

### Describe alternatives you've considered

I don't describe alternates beacause i dont know.

### Additional context

Please,do this
Its in my wishlist

**Comment by ZaptorZap** [comment] 2022-11-18 08:58
This is also a duplicate of #475 unfortunately.

**Closed by ZaptorZap** 2022-11-18 08:58 UTC
Labels: improvement
