### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by JJSarambao** [tetrio/issues#421] opened 2020-07-10 08:59 UTC
### Describe the bug/issue
I was just using the app for the second time, then the app logged me out, I tried entering my password multiple times and instead of logging me in, it logs me out. I tried restarting the app a couple of times but it still doesn't log me in at all

### Reproducing
I don't really know how did this happen. All I did was install the .deb file in my system, played the app for a bit, shut the computer down, turn on, open the app and then the app will log me out

### Expected behavior
Since it logs the user out, it needs to type the account password again. but then as soon as you click 'Login' a notification says 'You were logged out. Please log in again!' and then after logging in again, the notification will show up again telling you to log in again, and it will go on and on

### Screenshots
as seen in the screenshot, it shows the notification as I click the 'login' button
![Screenshot from 2020-07-10 16-53-45](https://user-images.githubusercontent.com/25699100/87136595-4d0d7300-c2ce-11ea-8634-3ed034b66238.png)

### Your setup
 - **OS and version**: Zorin OS 12.4 64-bit (Ubuntu 16.04 Xenial)

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by tilda** [comment] 2020-07-10 09:01
Known, see #419 #416. F5 will let you log in as usual

**Comment by ZaptorZap** [comment] 2020-07-10 09:01
Might I redirect you to #419, which has a solution to this issue. This is also a duplicate of #418, #416, and #415.

**Comment by o5k** [comment] 2020-07-10 12:13
DUplicate of #415 - hit F5 on this screen to fix the issue

**Closed by o5k** 2020-07-10 12:13 UTC
Labels: bug
