### ISSUE TITLE
Finesse Fault Bypass

### ISSUE THREAD

**Issue by Peterjoness** [tetrio/issues#1086] opened 2023-02-22 19:05 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

ChromeOS

### Browser and version

Chrome 110.0.5481.112

### Describe the bug/issue

When tapping the down arrow before hard dropping, a finesse fault will not be made. I think this is because finesse faults are ignored while soft dropping, so the player can perform actions such as T-spins. Because of this, tapping the down arrow tricks the program into thinking the player is soft dropping, and a finesse fault is not accounted for.

### Reproducing

1. Go to TETR.IO
2. Select any game mode with a finesse tracker
3. Make a finesse fault before hard dropping a tetromino
4. Tap the down arrow
5. Hard drop

### Expected behavior

A finesse fault should be made.

**Comment by ZaptorZap** [comment] 2023-02-23 03:51
Duplicate of #671

**Closed by ZaptorZap** 2023-02-23 03:51 UTC
Labels: bug
