### ISSUE TITLE
Desktop version installing

### ISSUE THREAD

**Issue by Gigabaka** [tetrio/issues#908] opened 2022-03-18 07:46 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 99.0.4844.51

### Describe the bug/issue

Browser version works fine, but desktop ins
talation stops at aaround 30%

### Expected behavior

The program to download

### Screenshots

![image](https://user-images.githubusercontent.com/101861621/158958262-9f643500-a08f-49e0-a807-7be5b2f9591d.png)

**Comment by ZaptorZap** [comment] 2022-03-19 23:07
'Tis but a duplicate of #570, sorry.

**Closed by ZaptorZap** 2022-03-19 23:07 UTC
Labels: bug
