### ISSUE TITLE
Add your own music in the desktop version

### ISSUE THREAD

**Issue by JustSquid** [tetrio/issues#850] opened 2021-12-12 14:47 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I recently noticed the customization config, and how it was looking a little dry with features. The only thing I see is a place to add URLs for background images and that's that.  Sometimes I like to play my own music with the use of a separate music player, and thought an embedded player for custom music would be a nice feature to add to the customization menu.

### Describe the solution you'd like

I would like the user to be able to import their own music files in the desktop version and have the option to switch between Tetr.io OST and custom songs. This could be done by clicking on a button in Config, selecting a folder with the custom music, and selecting an option in the music menu for "Custom".

### Describe alternatives you've considered

An alternative would be having a built in directory where users could drag n' drop their files into and the music getting automatically added to the pool. The above features for custom songs only would pass through here as well.

### Additional context

This was already implemented with https://gitlab.com/UniQMG/tetrio-plus/-/wikis/Custom-music, and I would like to see this as a mainline feature

**Comment by o5k** [comment] 2022-02-24 00:10
Dupe of #187

**Closed by o5k** 2022-02-24 00:10 UTC
Labels: improvement
