### ISSUE TITLE
When I boot up tetr.io desktop it gives me this screen and does not give me a captcha.

### ISSUE THREAD

**Issue by juheva1993** [tetrio/issues#1177] opened 2023-08-30 21:47 UTC
When I boot up tetr.io desktop it gives me this screen and does not give me a captcha.
![Capturat](https://github.com/tetrio/issues/assets/29875940/7a5224db-c5ea-45e3-b09c-6f05a8a03a33)

**Comment by ZaptorZap** [comment] 2023-08-30 21:51
Duplicate of #1171

**Closed by ZaptorZap** 2023-08-30 21:51 UTC
Labels: bug, user couldn't be bothered with the issue template
