### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by Maylit336** [tetrio/issues#1225] opened 2023-12-14 05:05 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I play on my phone. and I don't have access to tetrio plus. But I know I can’t create my own Skins or download someone and put in game. In general, it would be an interesting idea to open certain Skins or sounds when you reach a level. or maybe if you get this or that badges. or for example Rank. ah, banality. but it would be cool for others to see your skins. oh and yes. About this, Players cannot see your custom Skins and hear custom Sfx

### Describe the solution you'd like

Add the ability to add your own block texture or skins or sfx in the settings (such as a custom background.) 
add the ability to see skins, textures or even hear custom Sfx from other players. It would be cool to be individual and for the level to also have a purpose. 

### Describe alternatives you've considered

Add Openability of skins. For example, I got to this level and got this skin. or received such a Badge, received the corresponding skin. Or, for example, you reached this or that rank, received the corresponding Skin or sfx. which can be changed in the settings. 

### Additional context

yes, its kinda corny.  but in tetrio 99 you can also install many different skins, sfx, backgrounds, even the music changes. By the way about music. Can I create my own playlist with music? Of course it's easier to reproduce it yourself. but it would be cool if you went into a match and the music that you put into the game was playing. 
There's a Russian dude who's about level 5000. he saved it, saved it. and for what? He didn’t get anything for it, but maybe he did get something. but to be honest, there is little that is interesting about the player's level. Well, you know that he has such a level, but you won’t get anything for him. as well as for the rank, although la. you will receive it, but it would be interesting to receive a real reward, so you received this or that badge, here is the skin for you, play with it. be different from others. I'm probably asking a lot, but it wouldn't even be a bad idea. I would like a Tetris that has everything. and tetrio has all hope.

**Comment by ZaptorZap** [comment] 2023-12-14 05:07
Duplicate of #359

**Closed by ZaptorZap** 2023-12-14 05:07 UTC
Labels: improvement

**Comment by Maylit336** [comment] 2023-12-14 05:09
gee. didn't even know.
