### ISSUE TITLE
More friendly mode requirements

### ISSUE THREAD

**Issue by chullin** [tetrio/issues#798] opened 2021-10-24 12:44 UTC
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

在使用者自定義房間中，是否能設定等級限制，或是設定 LEAGUE 中分數多少以下才能進行遊玩

In the user-defined room, can you set the level limit or set the score in LEAGUE before you can play

### Describe the solution you'd like

Same as above

### Describe alternatives you've considered

Same as above

**Comment by ajs256** [comment] 2022-02-27 17:42
The AUTOHOST bot can set rank limits. See https://gitlab.com/Zudo/autohost/-/wikis/Get-Started for how to make an autohost room, and https://gitlab.com/Zudo/autohost/-/wikis/Participation-Rules for how to set participation rules.

**Comment by ZaptorZap** [comment] 2022-06-12 04:49
This's also a duplicate of #276 and (potentially) #486. Sorry about that.

**Closed by ZaptorZap** 2022-06-12 04:49 UTC
Labels: improvement
