### ISSUE TITLE
The desktop client install gets stuck at near half percent(duplicate)

### ISSUE THREAD

**Issue by VolkyWay** [tetrio/issues#910] opened 2022-03-19 21:11 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11 Beta build 22000.556

### Browser and version

Firefox Version 98.0.1(64-Bit)

### Describe the bug/issue

I rage uninstalled the desktop client a few weeks ago( :D ) and decided to redownload the game. While downloading it get stuck everytime at this 
![image](https://user-images.githubusercontent.com/101951048/159138497-aaea2648-e41d-42db-aa21-95a990ac6e94.png)

### Reproducing

1. download the game 🗿

### Expected behavior

Shouldn't get stuck

### Screenshots

![image](https://user-images.githubusercontent.com/101951048/159138518-e72d30ce-7dc5-452b-8fdc-5d0d2189525d.png)

**Comment by ZaptorZap** [comment] 2022-03-19 23:06
Thank you very much for self-labeling this as a duplicate issue, although you did fail to mention what issue it was a duplicate of. **(#570)**
I'll be closing this now.

**Closed by ZaptorZap** 2022-03-19 23:06 UTC
Labels: bug
