### ISSUE TITLE
the game interface is too small on the Android mobile devices

### ISSUE THREAD

**Issue by Antoni0111** [tetrio/issues#954] opened 2022-05-28 08:10 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Android 12 (One UI 4.1)

### Browser and version

Microsoft Edge 101.0.1210.53 

### Describe the bug/issue

The game can run on the android, but it is too small, plz adjust the size of interface on mobile devices

### Expected behavior

Plz make the interface bigger to see more easily

### Screenshots

![Screenshot_20220528-160620_Edge](https://user-images.githubusercontent.com/103315112/170816793-72190ac7-c53f-430c-9e69-a85447b8cf35.jpg)

**Comment by ZaptorZap** [comment] 2022-05-28 08:12
Please try turning your phone sideways—and then check out #950, since this is a duplicate of that.

**Closed by ZaptorZap** 2022-05-28 08:12 UTC
Labels: bug
