### ISSUE TITLE
Different Language Options

### ISSUE THREAD

**Issue by notypey** [tetrio/issues#414] opened 2020-07-08 20:21 UTC
### Is your feature request related to a problem? Please describe.

Kind of, since I failed to recommend the game to some of my friends who are not familiar with English.
### Describe the solution you'd like
I am sure people would be willing to contribute translations in different languages to the game. 
### Describe alternatives you've considered
Using google translate on the page is possible, but the translation is far from accurate considering the terminologies used.

**Comment by o5k** [comment] 2020-07-08 20:22
duplicate of #102

**Closed by o5k** 2020-07-08 20:22 UTC
Labels: improvement
