### ISSUE TITLE
gaining a loss in the tetra laugue with no opponent

### ISSUE THREAD

**Issue by Rosalia-m** [tetrio/issues#1179] opened 2023-09-06 08:50 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Google chrome

### Describe the bug/issue

I was in the queue for the tetra league, I disconnected before it turned white, saying I found an opponent, so i wasn't even in a game when i disconnected. It later said i was awarded a loss and the points were taken from me. Even if it did turn white in previous games i've been in a loss or victory isnt awarded unless the countdown starts and so points being taken from me when I wasn't even passed the queue isn't right nor is normal.

### Expected behavior

I expected not to earn a loss. I understand that i got disconnected and I know that if i was in a match after the countdown i would be awarded that loss but i wasn't in a match and so should never have lost those points.

**Comment by ZaptorZap** [comment] 2023-09-06 09:07
I'm inclined to believe this is a benign duplicate of #978. Match cancellation, an intended mechanic, just isn't very robust right now—canceled matches **won't** appear in your Tetra League record.

**Closed by ZaptorZap** 2023-09-06 09:07 UTC
Labels: bug
