### ISSUE TITLE
Allow for customizable dimming of swapped-out hold piece

### ISSUE THREAD

**Issue by godotgamedeveloper** [tetrio/issues#999] opened 2022-08-15 21:19 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Many players see pieces by their color rather than (or in addition to) by their shape.  Swapped-out hold pieces are completely grayed out until the current piece is placed, making the color unrecognizable (although the shape is still recognizable).  This can be confusing and frustrating for players who rely on color.

The issue is that the piece is grayed out so much that the player can no longer discern the original color, while there is also no option to lessen the amount of graying-out to accommodate the needs of the player. 

### Describe the solution you'd like

New slider for dimming, 100% being what it is currently (this can be the default), and 0% being no visual change to the swapped-out hold piece – inbetweens would basically just change the brightness of the piece.

### Describe alternatives you've considered

An alternative would be to allow an option to convey that a piece has already been swapped using something other than dimming, such adding a symbol of a red circle with a diagonal line over it (prohibition sign).

### Additional context

See also: https://github.com/tetrio/issues/issues/76

**Comment by ZaptorZap** [comment] 2022-08-16 04:26
Sorry about that, but this is a carbon copy duplicate of that additional issue you mentioned. Please try to **comment** on closed issues you are still interested in instead of opening new ones! I do _at least_ read everything that goes through this repository.

**Closed by ZaptorZap** 2022-08-16 04:26 UTC
Labels: improvement

**Comment by godotgamedeveloper** [comment] 2022-08-16 05:08
@ZaptorZap My bad for not explaining this when citing the older issue, but these issues to me while close are not identical.  I made a new issue to pertain specifically to _swapped-out_ hold pieces.  The old issue misstates the problem (or is misleading at best) because it implies that held pieces are always dimmed (or only dimmed when not yet swapped out), which isn't the case.  The old issue's author later admitted his/her own misunderstanding and asked for the old issue to be closed.  That having been said, if we are going with the older issue, we can consider changing it to refer to swapped-out hold pieces specifically.

**Comment by ZaptorZap** [comment] 2022-08-16 05:12
I would say the request is still clear enough to warrent preferring that one over this, even if originally created without the distinction of a hold cooldown. The piece **does** dim, even if not forever, and the request is still for a method of customizing this behavior. I could change the title, but "hold purgatory" is still descriptive enough for me to not imply that the piece shall forever remain unholdable.
