### ISSUE TITLE
ads causing lag during multiplayer games

### ISSUE THREAD

**Issue by 2CARECR0W** [tetrio/issues#1022] opened 2022-09-23 07:43 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

latest chrome OS

### Browser and version

chrome for chromebook

### Describe the bug/issue

when i play in multiplayer games, ads refreshing at the bottom of the screen make my game lag reall bad for a moment. it causes misdrops among other unwanted things in-game, and ive lost games to it.
i dont mind having ads on the main site at all, but on the page where im playing and ad changes cause that much of an issue sucks at the very least

### Reproducing

1. go to any multiplayer game that will have an ad on the page
2. play game

### Expected behavior

at some point the ad on screen changes and causes lag

**Comment by ZaptorZap** [comment] 2022-09-23 07:46
Duplicate of #1004 and #982.

**Closed by ZaptorZap** 2022-09-23 07:46 UTC
Labels: bug
