### ISSUE TITLE
Ads blocking screen in tetra league

### ISSUE THREAD

**Issue by Rosalia-m** [tetrio/issues#1181] opened 2023-09-20 06:48 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Google chrome

### Describe the bug/issue

When playing the the tetra league an add takes up the upper part of the screen which makes it impossible to see what block is next and to see where i place the block if i have to many uncompleted rows. Theres also no way for me to exit out of it.

### Expected behavior

No ads taking up most of the top screen. maybe an ad on the side or bottom.

**Comment by ZaptorZap** [comment] 2023-10-29 10:51
Duplicate of #1122

**Closed by ZaptorZap** 2023-10-29 10:51 UTC
Labels: bug
