### ISSUE TITLE
out of foucs

### ISSUE THREAD

**Issue by joa725** [tetrio/issues#1201] opened 2023-11-09 01:10 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

ios 14.1

### Browser and version

chrome 94

### Describe the bug/issue

i was playing the game, and suddenly the 'out of focus' thing popped out, it told me to click to return, but it never returned, this happened so many times during games today.

### Expected behavior

never happen again.

### Screenshots

![Uploading 截圖 2023-11-09 09.07.00.png…]()

**Comment by ZaptorZap** [comment] 2023-11-09 01:13
Duplicate of #1198

**Closed by ZaptorZap** 2023-11-09 01:13 UTC
Labels: bug
