### ISSUE TITLE
Play offline if server is down

### ISSUE THREAD

**Issue by jez9999** [tetrio/issues#1066] opened 2022-12-23 19:15 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Right now there's an outage with tetr.io's server.  It'd be nice to be able to play offline modes like Zen mode anyway.

### Describe the solution you'd like

Ability to play offline even when tetr.io can't connect to the server.

### Describe alternatives you've considered

Erm... play another Tetris game?  lol

**Comment by ZaptorZap** [comment] 2022-12-23 22:07
Duplicate of #521

**Closed by ZaptorZap** 2022-12-23 22:07 UTC
Labels: improvement
