### ISSUE TITLE
Pentomino

### ISSUE THREAD

**Issue by WeirdBoi12408** [tetrio/issues#924] opened 2022-04-10 02:05 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I have to go to Jstris for pentominos, and the rotation system for it isn't very good. I've seen that you were able to implement it on the april fool's update, I suppose it's sort of easy to implement in this great game.

### Describe the solution you'd like

Add a pentomino mode in a custom game / room

### Describe alternatives you've considered

Going on Jstris is an alternative, although it doesn't feel right without all of the fancy effects and without people chatting with me

### Additional context

It's fun once you get to try it.

**Comment by WeirdBoi12408** [comment] 2022-04-13 21:23
The attack table should be like the normal attack table but the attack for the TST is the attack for the pentris

**Comment by orangetriangle** [comment] 2022-04-14 15:21
This is a duplicate of #561 i think

**Comment by ZaptorZap** [comment] 2022-04-14 16:10
Oh I just **knew** someone had to have mentioned this *somewhere* before, but I couldn't find that when I tried searching.

**Closed by ZaptorZap** 2022-04-14 16:10 UTC
Labels: improvement, feat: engine

**Comment by WeirdBoi12408** [comment] 2022-04-21 22:27
thanks for telling me this is a duplicate
