### ISSUE TITLE
replay slider bug

### ISSUE THREAD

**Issue by hs47kim** [tetrio/issues#1231] opened 2023-12-21 23:15 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Tetrio Browser

### Describe the bug/issue

When using the slider to speed up the replay, it ended up showing an unrecognizable board state which is most evident by the fact that I won round 12/12 whilst the replay shows me losing. If left alone it shows what happened in the actual game. Tetrio channel also shows the actual events.

### Reproducing

Not too sure how to reproduce it. Seems rare as it's the first time seeing this.

### Expected behavior

Replay to show the actual events.

### Screenshots

![unknown_2023 12 21-17 39_1](https://github.com/tetrio/issues/assets/34083711/cfde0799-a590-4fc1-a8e9-9dae4bfea62c)
![image](https://github.com/tetrio/issues/assets/34083711/41d2f944-3a8c-489f-8922-07712235f52f)

**Comment by p1nkl0bst3r** [comment] 2023-12-27 14:10
duplicate of #886

**Comment by ZaptorZap** [comment] 2023-12-27 14:13
Concurred

**Closed by ZaptorZap** 2023-12-27 14:13 UTC
Labels: bug
