### ISSUE TITLE
Offline tetr.io

### ISSUE THREAD

**Issue by AndrewAnims** [tetrio/issues#744] opened 2021-08-10 12:07 UTC
### Checklist (issue will be disregarded & closed if incomplete!)

- [ ] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
I wanted to have a offline mode for tetrio because my wifi goes out sometimes and i would want to play tetris without wifi, and don't even suggest tetris mobile

### Describe the solution you'd like
You can add a option to disable update checkers completely (but if wifi is detected it would check wifi)
### Describe alternatives you've considered
You can just make another tetrio game but only for offline but the first solution is more better since there is a marathon, sprint, and blitz already on the game

**Comment by sayit358** [comment] 2021-08-10 15:08
Pretty sure this is a dupe of #521.

**Comment by ZaptorZap** [comment] 2021-08-10 19:51
Agreed. It's an interesting idea to borrow a couple pages from [Tetra Offline](https://github.com/Juan-Cartes/Tetra-Offline/), but it also sounds a bit superfluous.

**Closed by ZaptorZap** 2021-08-10 19:51 UTC
Labels: improvement
